### ISSUE TITLE
ImportError: No module named jss when using jssimporter 1.0.0 or later and fresh install

### ISSUE THREAD

**Issue by danengh** [jssimporter/jss_helper#26]
With jssimporter 1.0.0 and later, the path to the module jss was moved. In order to get jss_helper to work, a line of code pointing to the new location needs to be added in both /usr/local/bin/jss_helper_lib/tools.py and /usr/local/bin/jss_helper_lib/actions.py.

After import sys but before import jss, insert the following code:

sys.path.insert(0, '/Library/Application Support/JSSImporter')

**Comment by grahampugh** [comment]
Hi all, can you try 2.1.0b1? Note that you should already have JSSImporter set up, because this new version relies on the latest python-jss which is installed by JSSImporter.
