### ISSUE TITLE
"Scoped" verb doesn't consider Configuration Profiles

### ISSUE THREAD

**Issue by homebysix** [jssimporter/jss_helper#4]
I used the `scoped` verb produced a list of groups and their associated policies, and filtered for the ones that said "no results found." Many of the groups with no results found were in fact used for Configuration Profile scopes. Is there a way for jss_helper to take that into consideration?

**Comment by sheagcraig** [comment]
That makes sense to me. Originally this command was named policies_by_group or something like that. After renaming it, including other scoped things makes sense.

**Comment by sheagcraig** [comment]
Added for the next release (in testing now).
